version: '3.8'

services:
  app:
    build: .
    command: poetry run python app.py
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:30:8000"
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ADMIN_USERNAME=admin@admin.ru
      - ADMIN_PASSWORD=admin
      - EMAIL_LOGIN=parking_test01@sibnet.ru
      - EMAIL_PASSWORD=parking_test01
  db:
    image: alpine
    volumes:
      - sqlite_data:/app
    command: sh -c "touch /app/app.db && chown 1000:1000 /app/app.db && chmod 777 /app/app.db"
    expose:
      - 8000
volumes:
   sqlite_data:
